name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P frontend-build-and-transfer
